### PR TITLE
Change repository due to docker rate limitations

### PR DESCRIPTION
**Pull request by pwsh**
Changed linuxserver.io repository to the ghcr.io prefix per the linuxserver.io team due to the rate limits now being imposed by docker.com

### CODE REVIEW

**Comment by doob187** [comment]
Preview is wrong 

inuxserver/radarr:nightly


Tag | Description
-- | --
latest | Stable Radarr releases
develop | Radarr releases from their develop branch
nightly | Radarr releases from their nightly branch

**Comment by doob187** [comment]
@pwsh @timekills

**Comment by doob187** [comment]
https://github.com/PGBlitz/Apps-Core/pull/42

**Comment by timekills** [comment]
I was under the impression that the watchtower interval setting ensured the checks for new repositories would not exceed the free use of pulls for users from docker.com

**Comment by pwsh** [comment]
All I know is I have been hitting the limits anytime I add a new app. I figured this change would match what Linuxserver.io recommends and also give more headroom for pulling containers.

**Comment by timekills** [comment]
Have you verified all these changes worked using your personal github pull?

**Pull request closed without merging**
